spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: Pstagram

  profiles:
    active: local


logging:
  level:
    org.hibernate.SQL: debug

messages:
  basename: messages
  encoding: UTF-8


