spring:
  jpa:
    hibernate:
      ddl-auto: create # \uBC30\uD3EC\uD560\uB54C none\uC73C\uB85C \uBC14\uAFD4\uC8FC\uC138\uC6A5

  datasource:
    url: jdbc:mysql://localhost:3306/Pschema
    username: \uB2C9\uB124\uC784
    password: \uBE44\uBC00\uBC88\uD638
    driver-class-name: com.mysql.cj.jdbc.Driver
